import type { Metadata } from 'next'
import { Karla } from 'next/font/google'
import './globals.css'
import 'react-phone-input-2/lib/style.css'
import StyledComponentsRegistry from '@/lib/AntdesignRegistry'

const karla = Karla({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Education Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
